name: Fly Deploy
on:
    push:
        branches:
            - main
env:
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
    deploy:
        name: Deploy app
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
            - run: npm ci
            - run: npm run test
            - run: npm run build
            - run: flyctl deploy --remote-only
