name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - uses: actions/setup-node@v3
          with:
            node-version: 14
        - run: npm ci
        - run: npm run build
        - run: flyctl deploy --remote-only
